// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast
{
    public static class GetRunbook
    {
        /// <summary>
        /// A Runbook is a compilation of routine procedures and operations that are documented for reference while working on a critical incident. Sometimes, it can also be referred to as a Playbook.Use this data source to get information about a specific Runbook that you can use for other Squadcast resources.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Squadcast = Pulumi.Squadcast;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var test = Squadcast.GetRunbook.Invoke(new()
        ///     {
        ///         Name = squadcast_runbook.Test.Name,
        ///         TeamId = "team id",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetRunbookResult> InvokeAsync(GetRunbookArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRunbookResult>("squadcast:index/getRunbook:getRunbook", args ?? new GetRunbookArgs(), options.WithDefaults());

        /// <summary>
        /// A Runbook is a compilation of routine procedures and operations that are documented for reference while working on a critical incident. Sometimes, it can also be referred to as a Playbook.Use this data source to get information about a specific Runbook that you can use for other Squadcast resources.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Squadcast = Pulumi.Squadcast;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var test = Squadcast.GetRunbook.Invoke(new()
        ///     {
        ///         Name = squadcast_runbook.Test.Name,
        ///         TeamId = "team id",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetRunbookResult> Invoke(GetRunbookInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRunbookResult>("squadcast:index/getRunbook:getRunbook", args ?? new GetRunbookInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRunbookArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the Runbook
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// Team id.
        /// </summary>
        [Input("teamId", required: true)]
        public string TeamId { get; set; } = null!;

        public GetRunbookArgs()
        {
        }
        public static new GetRunbookArgs Empty => new GetRunbookArgs();
    }

    public sealed class GetRunbookInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the Runbook
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Team id.
        /// </summary>
        [Input("teamId", required: true)]
        public Input<string> TeamId { get; set; } = null!;

        public GetRunbookInvokeArgs()
        {
        }
        public static new GetRunbookInvokeArgs Empty => new GetRunbookInvokeArgs();
    }


    [OutputType]
    public sealed class GetRunbookResult
    {
        /// <summary>
        /// Runbooks owner
        /// </summary>
        public readonly ImmutableArray<Outputs.GetRunbookEntityOwnerResult> EntityOwners;
        /// <summary>
        /// Runbook id.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the Runbook
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Step by Step instructions, you can add as many steps as you want, supports markdown formatting.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetRunbookStepResult> Steps;
        /// <summary>
        /// Team id.
        /// </summary>
        public readonly string TeamId;

        [OutputConstructor]
        private GetRunbookResult(
            ImmutableArray<Outputs.GetRunbookEntityOwnerResult> entityOwners,

            string id,

            string name,

            ImmutableArray<Outputs.GetRunbookStepResult> steps,

            string teamId)
        {
            EntityOwners = entityOwners;
            Id = id;
            Name = name;
            Steps = steps;
            TeamId = teamId;
        }
    }
}
