// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast
{
    /// <summary>
    /// [Routing rules](https://support.squadcast.com/docs/alert-routing) allows you to ensure that alerts are routed to the right responder with the help of `event tags` attached to them.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Squadcast = Pulumi.Squadcast;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var exampleTeam = Squadcast.GetTeam.Invoke(new()
    ///     {
    ///         Name = "example team name",
    ///     });
    /// 
    ///     var exampleUser = Squadcast.GetUser.Invoke(new()
    ///     {
    ///         Email = "test@example.com",
    ///     });
    /// 
    ///     var exampleService = Squadcast.GetService.Invoke(new()
    ///     {
    ///         Name = "example service name",
    ///         TeamId = exampleTeam.Apply(getTeamResult =&gt; getTeamResult.Id),
    ///     });
    /// 
    ///     var exampleEscalaionPolicy = Squadcast.GetEscalationPolicy.Invoke(new()
    ///     {
    ///         Name = "example escalation policy name",
    ///         TeamId = exampleTeam.Apply(getTeamResult =&gt; getTeamResult.Id),
    ///     });
    /// 
    ///     var exampleSquad = Squadcast.GetSquad.Invoke(new()
    ///     {
    ///         Name = "example squad name",
    ///         TeamId = exampleTeam.Apply(getTeamResult =&gt; getTeamResult.Id),
    ///     });
    /// 
    ///     var exampleRoutingRules = new Squadcast.RoutingRules("exampleRoutingRules", new()
    ///     {
    ///         TeamId = exampleTeam.Apply(getTeamResult =&gt; getTeamResult.Id),
    ///         ServiceId = exampleService.Apply(getServiceResult =&gt; getServiceResult.Id),
    ///         Rules = new[]
    ///         {
    ///             new Squadcast.Inputs.RoutingRulesRuleArgs
    ///             {
    ///                 IsBasic = false,
    ///                 Expression = "payload[\"event_id\"] == 40",
    ///                 RouteToId = Output.Tuple(exampleUser, exampleSquad, exampleEscalaionPolicy).Apply(values =&gt;
    ///                 {
    ///                     var exampleUser = values.Item1;
    ///                     var exampleSquad = values.Item2;
    ///                     var exampleEscalaionPolicy = values.Item3;
    ///                     return exampleUser.Apply(getUserResult =&gt; getUserResult.Id) / exampleSquad.Apply(getSquadResult =&gt; getSquadResult.Id) / exampleEscalaionPolicy.Apply(getEscalationPolicyResult =&gt; getEscalationPolicyResult.Id);
    ///                 }),
    ///                 RouteToType = "user/squad/escalation_policy",
    ///             },
    ///             new Squadcast.Inputs.RoutingRulesRuleArgs
    ///             {
    ///                 IsBasic = true,
    ///                 BasicExpressions = new[]
    ///                 {
    ///                     new Squadcast.Inputs.RoutingRulesRuleBasicExpressionArgs
    ///                     {
    ///                         Lhs = "payload[\"foo\"]",
    ///                         Rhs = "bar",
    ///                     },
    ///                 },
    ///                 RouteToId = Output.Tuple(exampleUser, exampleSquad, exampleEscalaionPolicy).Apply(values =&gt;
    ///                 {
    ///                     var exampleUser = values.Item1;
    ///                     var exampleSquad = values.Item2;
    ///                     var exampleEscalaionPolicy = values.Item3;
    ///                     return exampleUser.Apply(getUserResult =&gt; getUserResult.Id) / exampleSquad.Apply(getSquadResult =&gt; getSquadResult.Id) / exampleEscalaionPolicy.Apply(getEscalationPolicyResult =&gt; getEscalationPolicyResult.Id);
    ///                 }),
    ///                 RouteToType = "user/squad/escalation_policy",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// teamID:serviceID Use 'Get All Teams' and 'Get All Services' APIs to get the id of the team and service respectively
    /// 
    /// ```sh
    ///  $ pulumi import squadcast:index/routingRules:RoutingRules test 62d2fe23a57381088224d726:62da76c088f407f9ca756ca5
    /// ```
    /// </summary>
    [SquadcastResourceType("squadcast:index/routingRules:RoutingRules")]
    public partial class RoutingRules : global::Pulumi.CustomResource
    {
        [Output("rules")]
        public Output<ImmutableArray<Outputs.RoutingRulesRule>> Rules { get; private set; } = null!;

        /// <summary>
        /// Service id.
        /// </summary>
        [Output("serviceId")]
        public Output<string> ServiceId { get; private set; } = null!;

        /// <summary>
        /// Team id.
        /// </summary>
        [Output("teamId")]
        public Output<string> TeamId { get; private set; } = null!;


        /// <summary>
        /// Create a RoutingRules resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RoutingRules(string name, RoutingRulesArgs args, CustomResourceOptions? options = null)
            : base("squadcast:index/routingRules:RoutingRules", name, args ?? new RoutingRulesArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RoutingRules(string name, Input<string> id, RoutingRulesState? state = null, CustomResourceOptions? options = null)
            : base("squadcast:index/routingRules:RoutingRules", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RoutingRules resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RoutingRules Get(string name, Input<string> id, RoutingRulesState? state = null, CustomResourceOptions? options = null)
        {
            return new RoutingRules(name, id, state, options);
        }
    }

    public sealed class RoutingRulesArgs : global::Pulumi.ResourceArgs
    {
        [Input("rules", required: true)]
        private InputList<Inputs.RoutingRulesRuleArgs>? _rules;
        public InputList<Inputs.RoutingRulesRuleArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Inputs.RoutingRulesRuleArgs>());
            set => _rules = value;
        }

        /// <summary>
        /// Service id.
        /// </summary>
        [Input("serviceId", required: true)]
        public Input<string> ServiceId { get; set; } = null!;

        /// <summary>
        /// Team id.
        /// </summary>
        [Input("teamId", required: true)]
        public Input<string> TeamId { get; set; } = null!;

        public RoutingRulesArgs()
        {
        }
        public static new RoutingRulesArgs Empty => new RoutingRulesArgs();
    }

    public sealed class RoutingRulesState : global::Pulumi.ResourceArgs
    {
        [Input("rules")]
        private InputList<Inputs.RoutingRulesRuleGetArgs>? _rules;
        public InputList<Inputs.RoutingRulesRuleGetArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Inputs.RoutingRulesRuleGetArgs>());
            set => _rules = value;
        }

        /// <summary>
        /// Service id.
        /// </summary>
        [Input("serviceId")]
        public Input<string>? ServiceId { get; set; }

        /// <summary>
        /// Team id.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        public RoutingRulesState()
        {
        }
        public static new RoutingRulesState Empty => new RoutingRulesState();
    }
}
