// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("squadcast");

/**
 * The refresh token, This can be created from user profile
 */
export declare const refreshToken: string | undefined;
Object.defineProperty(exports, "refreshToken", {
    get() {
        return __config.get("refreshToken");
    },
    enumerable: true,
});

/**
 * The region you are currently hosted on.Supported values are "us" and "eu"
 */
export declare const region: string | undefined;
Object.defineProperty(exports, "region", {
    get() {
        return __config.get("region");
    },
    enumerable: true,
});

