// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Outputs
{

    [OutputType]
    public sealed class EscalationPolicyRule
    {
        public readonly int DelayMinutes;
        public readonly ImmutableArray<string> NotificationChannels;
        /// <summary>
        /// repeat this rule
        /// </summary>
        public readonly Outputs.EscalationPolicyRuleRepeat? Repeat;
        public readonly Outputs.EscalationPolicyRuleRoundRobin? RoundRobin;
        public readonly ImmutableArray<Outputs.EscalationPolicyRuleTarget> Targets;

        [OutputConstructor]
        private EscalationPolicyRule(
            int delayMinutes,

            ImmutableArray<string> notificationChannels,

            Outputs.EscalationPolicyRuleRepeat? repeat,

            Outputs.EscalationPolicyRuleRoundRobin? roundRobin,

            ImmutableArray<Outputs.EscalationPolicyRuleTarget> targets)
        {
            DelayMinutes = delayMinutes;
            NotificationChannels = notificationChannels;
            Repeat = repeat;
            RoundRobin = roundRobin;
            Targets = targets;
        }
    }
}
