// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Outputs
{

    [OutputType]
    public sealed class EscalationPolicyRuleRepeat
    {
        /// <summary>
        /// The number of minutes to wait before repeating the escalation policy
        /// </summary>
        public readonly int DelayMinutes;
        /// <summary>
        /// The number of times you want this escalation policy to be repeated, maximum allowed to repeat 3 times
        /// </summary>
        public readonly int Times;

        [OutputConstructor]
        private EscalationPolicyRuleRepeat(
            int delayMinutes,

            int times)
        {
            DelayMinutes = delayMinutes;
            Times = times;
        }
    }
}
