// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Outputs
{

    [OutputType]
    public sealed class GetEscalationPolicyEntityOwnerResult
    {
        /// <summary>
        /// Escalation policy owner id.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Escalation policy owner type. (user or squad or team)
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetEscalationPolicyEntityOwnerResult(
            string id,

            string type)
        {
            Id = id;
            Type = type;
        }
    }
}
