// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Outputs
{

    [OutputType]
    public sealed class GetTeamRoleResult
    {
        public readonly ImmutableArray<string> Abilities;
        /// <summary>
        /// Squadcast has one default team and this field let's us know if this is the default team.
        /// </summary>
        public readonly bool Default;
        /// <summary>
        /// Team id.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the Team.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetTeamRoleResult(
            ImmutableArray<string> abilities,

            bool @default,

            string id,

            string name)
        {
            Abilities = abilities;
            Default = @default;
            Id = id;
            Name = name;
        }
    }
}
