// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Outputs
{

    [OutputType]
    public sealed class GetTeamMemberResult
    {
        public readonly ImmutableArray<string> RoleIds;
        public readonly string UserId;

        [OutputConstructor]
        private GetTeamMemberResult(
            ImmutableArray<string> roleIds,

            string userId)
        {
            RoleIds = roleIds;
            UserId = userId;
        }
    }
}
