// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Outputs
{

    [OutputType]
    public sealed class RoutingRulesRule
    {
        /// <summary>
        /// The basic expression which needs to be evaluated to be true for this rule to apply.
        /// </summary>
        public readonly ImmutableArray<Outputs.RoutingRulesRuleBasicExpression> BasicExpressions;
        /// <summary>
        /// The expression which needs to be evaluated to be true for this rule to apply.
        /// </summary>
        public readonly string? Expression;
        /// <summary>
        /// is_basic will be true when users use the drop down selectors which will have lhs, op &amp; rhs value, whereas it will be false when they use the advanced mode and it would have the expression for it's value
        /// </summary>
        public readonly bool IsBasic;
        /// <summary>
        /// The id of the entity (user, escalation policy, squad) for which we are routing this incident.
        /// </summary>
        public readonly string RouteToId;
        /// <summary>
        /// Type of the entity for which we are routing this incident - User, Escalation Policy or Squad
        /// </summary>
        public readonly string RouteToType;

        [OutputConstructor]
        private RoutingRulesRule(
            ImmutableArray<Outputs.RoutingRulesRuleBasicExpression> basicExpressions,

            string? expression,

            bool isBasic,

            string routeToId,

            string routeToType)
        {
            BasicExpressions = basicExpressions;
            Expression = expression;
            IsBasic = isBasic;
            RouteToId = routeToId;
            RouteToType = routeToType;
        }
    }
}
