// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Outputs
{

    [OutputType]
    public sealed class SuppressionRulesRuleTimeslotCustom
    {
        public readonly string Repeats;
        public readonly int? RepeatsCount;
        public readonly string? RepeatsOnMonth;
        public readonly ImmutableArray<int> RepeatsOnWeekdays;

        [OutputConstructor]
        private SuppressionRulesRuleTimeslotCustom(
            string repeats,

            int? repeatsCount,

            string? repeatsOnMonth,

            ImmutableArray<int> repeatsOnWeekdays)
        {
            Repeats = repeats;
            RepeatsCount = repeatsCount;
            RepeatsOnMonth = repeatsOnMonth;
            RepeatsOnWeekdays = repeatsOnWeekdays;
        }
    }
}
