// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/valisinsights/pulumi-squadcast/sdk/go/squadcast/internal"
)

var _ = internal.GetEnvOrDefault

// The refresh token, This can be created from user profile
func GetRefreshToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "squadcast:refreshToken")
}

// The region you are currently hosted on.Supported values are "us" and "eu"
func GetRegion(ctx *pulumi.Context) string {
	return config.Get(ctx, "squadcast:region")
}
