// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package squadcast

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/valisinsights/pulumi-squadcast/sdk/go/squadcast/internal"
)

// Team roles are a way to define abilities/permissions for a user in the team. Each team role can be considered as a set of permissions that can be assigned to a user. Use this data source to get information about various team roles.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/valisinsights/pulumi-squadcast/sdk/go/squadcast"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := squadcast.LookupTeamRole(ctx, &squadcast.LookupTeamRoleArgs{
//				Name:   "testRole",
//				TeamId: "team id",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupTeamRole(ctx *pulumi.Context, args *LookupTeamRoleArgs, opts ...pulumi.InvokeOption) (*LookupTeamRoleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTeamRoleResult
	err := ctx.Invoke("squadcast:index/getTeamRole:getTeamRole", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTeamRole.
type LookupTeamRoleArgs struct {
	// TeamRole name.
	Name string `pulumi:"name"`
	// Team id.
	TeamId string `pulumi:"teamId"`
}

// A collection of values returned by getTeamRole.
type LookupTeamRoleResult struct {
	// All the abilities attached to a role.
	Abilities []string `pulumi:"abilities"`
	// Role is default.
	Default bool `pulumi:"default"`
	// Role id.
	Id string `pulumi:"id"`
	// TeamRole name.
	Name string `pulumi:"name"`
	// Team id.
	TeamId string `pulumi:"teamId"`
}

func LookupTeamRoleOutput(ctx *pulumi.Context, args LookupTeamRoleOutputArgs, opts ...pulumi.InvokeOption) LookupTeamRoleResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupTeamRoleResult, error) {
			args := v.(LookupTeamRoleArgs)
			r, err := LookupTeamRole(ctx, &args, opts...)
			var s LookupTeamRoleResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupTeamRoleResultOutput)
}

// A collection of arguments for invoking getTeamRole.
type LookupTeamRoleOutputArgs struct {
	// TeamRole name.
	Name pulumi.StringInput `pulumi:"name"`
	// Team id.
	TeamId pulumi.StringInput `pulumi:"teamId"`
}

func (LookupTeamRoleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTeamRoleArgs)(nil)).Elem()
}

// A collection of values returned by getTeamRole.
type LookupTeamRoleResultOutput struct{ *pulumi.OutputState }

func (LookupTeamRoleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTeamRoleResult)(nil)).Elem()
}

func (o LookupTeamRoleResultOutput) ToLookupTeamRoleResultOutput() LookupTeamRoleResultOutput {
	return o
}

func (o LookupTeamRoleResultOutput) ToLookupTeamRoleResultOutputWithContext(ctx context.Context) LookupTeamRoleResultOutput {
	return o
}

// All the abilities attached to a role.
func (o LookupTeamRoleResultOutput) Abilities() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupTeamRoleResult) []string { return v.Abilities }).(pulumi.StringArrayOutput)
}

// Role is default.
func (o LookupTeamRoleResultOutput) Default() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTeamRoleResult) bool { return v.Default }).(pulumi.BoolOutput)
}

// Role id.
func (o LookupTeamRoleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTeamRoleResult) string { return v.Id }).(pulumi.StringOutput)
}

// TeamRole name.
func (o LookupTeamRoleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTeamRoleResult) string { return v.Name }).(pulumi.StringOutput)
}

// Team id.
func (o LookupTeamRoleResultOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTeamRoleResult) string { return v.TeamId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTeamRoleResultOutput{})
}
