// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Inputs
{

    public sealed class DeduplicationRulesRuleArgs : global::Pulumi.ResourceArgs
    {
        [Input("basicExpressions")]
        private InputList<Inputs.DeduplicationRulesRuleBasicExpressionArgs>? _basicExpressions;

        /// <summary>
        /// The basic expression which needs to be evaluated to be true for this rule to apply.
        /// </summary>
        public InputList<Inputs.DeduplicationRulesRuleBasicExpressionArgs> BasicExpressions
        {
            get => _basicExpressions ?? (_basicExpressions = new InputList<Inputs.DeduplicationRulesRuleBasicExpressionArgs>());
            set => _basicExpressions = value;
        }

        /// <summary>
        /// Denotes if dependent services should also be deduplicated
        /// </summary>
        [Input("dependencyDeduplication")]
        public Input<bool>? DependencyDeduplication { get; set; }

        /// <summary>
        /// description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The expression which needs to be evaluated to be true for this rule to apply.
        /// </summary>
        [Input("expression")]
        public Input<string>? Expression { get; set; }

        /// <summary>
        /// is_basic will be true when users use the drop down selectors which will have lhs, op &amp; rhs value, whereas it will be false when they use the advanced mode and it would have the expression for it's value
        /// </summary>
        [Input("isBasic", required: true)]
        public Input<bool> IsBasic { get; set; } = null!;

        /// <summary>
        /// time unit (mins or hours)
        /// </summary>
        [Input("timeUnit")]
        public Input<string>? TimeUnit { get; set; }

        /// <summary>
        /// integer for time_unit
        /// </summary>
        [Input("timeWindow")]
        public Input<int>? TimeWindow { get; set; }

        public DeduplicationRulesRuleArgs()
        {
        }
        public static new DeduplicationRulesRuleArgs Empty => new DeduplicationRulesRuleArgs();
    }
}
