// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Inputs
{

    public sealed class EscalationPolicyRuleRoundRobinRotationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("delayMinutes")]
        public Input<int>? DelayMinutes { get; set; }

        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        public EscalationPolicyRuleRoundRobinRotationGetArgs()
        {
        }
        public static new EscalationPolicyRuleRoundRobinRotationGetArgs Empty => new EscalationPolicyRuleRoundRobinRotationGetArgs();
    }
}
