// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Inputs
{

    public sealed class EscalationPolicyEntityOwnerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Escalation policy owner id.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Escalation policy owner type. (user or squad or team)
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public EscalationPolicyEntityOwnerArgs()
        {
        }
        public static new EscalationPolicyEntityOwnerArgs Empty => new EscalationPolicyEntityOwnerArgs();
    }
}
