// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Inputs
{

    public sealed class ScheduleRotationV2ParticipantGroupArgs : global::Pulumi.ResourceArgs
    {
        [Input("participants")]
        private InputList<Inputs.ScheduleRotationV2ParticipantGroupParticipantArgs>? _participants;

        /// <summary>
        /// Group participants.
        /// </summary>
        public InputList<Inputs.ScheduleRotationV2ParticipantGroupParticipantArgs> Participants
        {
            get => _participants ?? (_participants = new InputList<Inputs.ScheduleRotationV2ParticipantGroupParticipantArgs>());
            set => _participants = value;
        }

        public ScheduleRotationV2ParticipantGroupArgs()
        {
        }
        public static new ScheduleRotationV2ParticipantGroupArgs Empty => new ScheduleRotationV2ParticipantGroupArgs();
    }
}
