// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Inputs
{

    public sealed class ScheduleV2EntityOwnerGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Schedule owner id.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Schedule owner type (user, team, squad).
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public ScheduleV2EntityOwnerGetArgs()
        {
        }
        public static new ScheduleV2EntityOwnerGetArgs Empty => new ScheduleV2EntityOwnerGetArgs();
    }
}
