// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Squadcast.Inputs
{

    public sealed class ScheduleRotationV2ShiftTimeslotGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defines the day of the week for the shift. If not specified, the timeslot is active on all days of the week.
        /// </summary>
        [Input("dayOfWeek")]
        public Input<string>? DayOfWeek { get; set; }

        /// <summary>
        /// Defines the duration of each shift. (in minutes)
        /// </summary>
        [Input("duration", required: true)]
        public Input<int> Duration { get; set; } = null!;

        /// <summary>
        /// Defines the start hour of the each shift in the schedule timezone.
        /// </summary>
        [Input("startHour", required: true)]
        public Input<int> StartHour { get; set; } = null!;

        /// <summary>
        /// Defines the start minute of the each shift in the schedule timezone.
        /// </summary>
        [Input("startMinute", required: true)]
        public Input<int> StartMinute { get; set; } = null!;

        public ScheduleRotationV2ShiftTimeslotGetArgs()
        {
        }
        public static new ScheduleRotationV2ShiftTimeslotGetArgs Empty => new ScheduleRotationV2ShiftTimeslotGetArgs();
    }
}
