// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to get information about a specific user that you can use for other Squadcast resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as squadcast from "@pulumi/squadcast";
 *
 * const test = squadcast.getUser({
 *     email: squadcast_user.test.email,
 * });
 * ```
 */
export function getUser(args: GetUserArgs, opts?: pulumi.InvokeOptions): Promise<GetUserResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("squadcast:index/getUser:getUser", {
        "email": args.email,
    }, opts);
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserArgs {
    /**
     * User email.
     */
    email: string;
}

/**
 * A collection of values returned by getUser.
 */
export interface GetUserResult {
    /**
     * Denotes the Permissions / abilities of the user.
     */
    readonly abilities: string[];
    /**
     * User email.
     */
    readonly email: string;
    /**
     * User first name.
     */
    readonly firstName: string;
    /**
     * User id.
     */
    readonly id: string;
    /**
     * Denotes if the user has verified their email or not.
     */
    readonly isEmailVerified: boolean;
    /**
     * Deprecated, this can be ignored.
     */
    readonly isOverrideDndEnabled: boolean;
    /**
     * Denotes if the user has verified their phone number or not.
     */
    readonly isPhoneVerified: boolean;
    /**
     * User last name.
     */
    readonly lastName: string;
    /**
     * User name, automatically computed from first name and last name.
     */
    readonly name: string;
    /**
     * User Personal Notification Rules.
     */
    readonly notificationRules: outputs.GetUserNotificationRule[];
    /**
     * User's personal on-call reminder notification rules.
     */
    readonly oncallReminderRules: outputs.GetUserOncallReminderRule[];
    /**
     * User phone number.
     */
    readonly phone: string;
    /**
     * User role.
     */
    readonly role: string;
    /**
     * User time_zone.
     */
    readonly timeZone: string;
}
/**
 * Use this data source to get information about a specific user that you can use for other Squadcast resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as squadcast from "@pulumi/squadcast";
 *
 * const test = squadcast.getUser({
 *     email: squadcast_user.test.email,
 * });
 * ```
 */
export function getUserOutput(args: GetUserOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetUserResult> {
    return pulumi.output(args).apply((a: any) => getUser(a, opts))
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserOutputArgs {
    /**
     * User email.
     */
    email: pulumi.Input<string>;
}
